import { OUROBOROS_RUNTIME_PATHS } from "./runtime-paths";

const RUNTIME_PROTECTION_SECTION = [
  "## Runtime File Guardrail",
  `Treat ${OUROBOROS_RUNTIME_PATHS.map((path) => `\`${path}\``).join(", ")} as Ouroboros runtime/control paths.`,
  "Do not modify, delete, recreate, clean, commit, or report these paths as task changedFiles.",
  "When inspecting repository status or verifying frontend-only changes, ignore these paths unless the task explicitly asks you to change Ouroboros itself.",
  "",
].join("\n");

export const DEFAULT_TASK_PROMPT_TEMPLATE = [
  "# Ouroboros Task",
  "",
  "Run Goal: {{runGoal}}",
  "",
  "## Run Context",
  "```json",
  "{{runContextJson}}",
  "```",
  "",
  "## Task",
  "Task ID: {{taskId}}",
  "Role: {{taskRole}}",
  "Goal: {{taskGoal}}",
  "",
  "## Instructions",
  "{{taskPrompt}}",
  "",
  RUNTIME_PROTECTION_SECTION,
  "## Done When",
  "{{doneWhenMarkdown}}",
  "",
  "## Dependency Attempts",
  "```json",
  "{{dependencyAttemptsJson}}",
  "```",
  "",
  "## Run Lessons",
  "```json",
  "{{runLessonsJson}}",
  "```",
  "",
  "{{activeGuardrailsMarkdown}}",
  "{{candidateGuardrailsMarkdown}}",
  "{{reusableExperienceEvidenceMarkdown}}",
  "## Required Output",
  "Return only JSON with this shape:",
  "Prefer the `actions` array for follow-up work and run decisions. Supported action types are createTasks, createRuns, and setRunDecision.",
  "```json",
  "{{requiredOutputJson}}",
  "```",
].join("\n");

export const LEGACY_DEFAULT_TASK_PROMPT_TEMPLATES = [
  [
    "# Ouroboros Task",
    "",
    "Run Goal: {{runGoal}}",
    "",
    "## Run Context",
    "```json",
    "{{runContextJson}}",
    "```",
    "",
    "## Task",
    "Task ID: {{taskId}}",
    "Role: {{taskRole}}",
    "Goal: {{taskGoal}}",
    "",
    "## Instructions",
    "{{taskPrompt}}",
    "",
    "## Done When",
    "{{doneWhenMarkdown}}",
    "",
    "## Dependency Attempts",
    "```json",
    "{{dependencyAttemptsJson}}",
    "```",
    "",
    "## Run Lessons",
    "```json",
    "{{runLessonsJson}}",
    "```",
    "",
    "{{candidateGuardrailsMarkdown}}",
    "{{reusableExperienceEvidenceMarkdown}}",
    "## Required Output",
    "Return only JSON with this shape:",
    "Prefer the `actions` array for follow-up work and run decisions. Supported action types are createTasks, createRuns, and setRunDecision.",
    "```json",
    "{{requiredOutputJson}}",
    "```",
  ].join("\n"),
  [
    "# Ouroboros Task",
    "",
    "Run Goal: {{runGoal}}",
    "",
    "## Run Context",
    "```json",
    "{{runContextJson}}",
    "```",
    "",
    "## Task",
    "Task ID: {{taskId}}",
    "Role: {{taskRole}}",
    "Goal: {{taskGoal}}",
    "",
    "## Instructions",
    "{{taskPrompt}}",
    "",
    "## Done When",
    "{{doneWhenMarkdown}}",
    "",
    "## Dependency Attempts",
    "```json",
    "{{dependencyAttemptsJson}}",
    "```",
    "",
    "## Promoted Guardrails",
    "{{promotedGuardrailsMarkdown}}",
    "",
    "## Reusable Experience Evidence",
    "{{reusableExperienceEvidenceMarkdown}}",
    "",
    "## Run Lessons",
    "```json",
    "{{runLessonsJson}}",
    "```",
    "",
    "## Required Output",
    "Return only JSON with this shape:",
    "Prefer the `actions` array for follow-up work and run decisions. Supported action types are createTasks, createRuns, and setRunDecision.",
    "```json",
    "{{requiredOutputJson}}",
    "```",
  ].join("\n"),
  [
    "# Ouroboros Task",
    "",
    "Run Goal: {{runGoal}}",
    "",
    "## Run Context",
    "```json",
    "{{runContextJson}}",
    "```",
    "",
    "## Task",
    "Task ID: {{taskId}}",
    "Role: {{taskRole}}",
    "Goal: {{taskGoal}}",
    "",
    "## Instructions",
    "{{taskPrompt}}",
    "",
    "## Done When",
    "{{doneWhenMarkdown}}",
    "",
    "## Dependency Attempts",
    "```json",
    "{{dependencyAttemptsJson}}",
    "```",
    "",
    "## Run Lessons",
    "```json",
    "{{runLessonsJson}}",
    "```",
    "",
    "## Required Output",
    "Return only JSON with this shape:",
    "```json",
    "{{requiredOutputJson}}",
    "```",
  ].join("\n"),
];

export const DEFAULT_VERIFIER_TASK_PROMPT_TEMPLATE = [
  "Verify the completed source task using repository state and recorded output.",
  "",
  "Source Task ID: {{sourceTaskId}}",
  "Source Worktree Path: {{sourceTaskWorktreePath}}",
  "",
  "Use the source worktree path above when it is recorded. Do not treat the verifier task's own fresh worktree as source evidence.",
  "When checking whether work remains, exclude the current verifier task and current running attempt from active-work counts.",
  "",
  RUNTIME_PROTECTION_SECTION,
  "## Source Output",
  "```json",
  "{{sourceOutputJson}}",
  "```",
  "",
  "{{sourceVerifierContractSection}}",
  "",
  "Return structured JSON. Use status blocked with concrete problems when verification cannot pass.",
].join("\n");

export const DEFAULT_REPAIR_TASK_PROMPT_TEMPLATE = [
  "Repair the failed verifier result.",
  "",
  "Verifier Task ID: {{verifierTaskId}}",
  "",
  RUNTIME_PROTECTION_SECTION,
  "## Verifier Output",
  "```json",
  "{{verifierOutputJson}}",
  "```",
  "",
  "Return structured JSON. Include changedFiles, checks, artifacts, and problems.",
].join("\n");

export const DEFAULT_CONTEXT_SUMMARY_PROMPT_TEMPLATE = [
  "# Ouroboros Context Summary",
  "",
  "Summarize one completed loop attempt into compact reusable context.",
  "",
  "## Attempt Output",
  "```json",
  "{{attemptOutputJson}}",
  "```",
  "",
  "## Required Output",
  "Return only JSON with this shape:",
  "```json",
  '{ "experience": { "summary": "one reusable success pattern", "evidence": {} }, "lesson": { "summary": "one failure or avoidance lesson", "evidence": {} } }',
  "```",
].join("\n");
