export const DEFAULT_TASK_PROMPT_TEMPLATE = [
  "# Ouroboros Task",
  "",
  "Run Goal: {{runGoal}}",
  "",
  "## Run Context",
  "```json",
  "{{runContextJson}}",
  "```",
  "",
  "## Task",
  "Task ID: {{taskId}}",
  "Role: {{taskRole}}",
  "Goal: {{taskGoal}}",
  "",
  "## Instructions",
  "{{taskPrompt}}",
  "",
  "## Done When",
  "{{doneWhenMarkdown}}",
  "",
  "## Dependency Attempts",
  "```json",
  "{{dependencyAttemptsJson}}",
  "```",
  "",
  "## Run Lessons",
  "```json",
  "{{runLessonsJson}}",
  "```",
  "",
  "## Required Output",
  "Return only JSON with this shape:",
  "```json",
  "{{requiredOutputJson}}",
  "```",
].join("\n");

export const DEFAULT_VERIFIER_TASK_PROMPT_TEMPLATE = [
  "Verify the completed source task using repository state and recorded output.",
  "",
  "Source Task ID: {{sourceTaskId}}",
  "",
  "## Source Output",
  "```json",
  "{{sourceOutputJson}}",
  "```",
  "",
  "Return structured JSON. Use status blocked with concrete problems when verification cannot pass.",
].join("\n");

export const DEFAULT_REPAIR_TASK_PROMPT_TEMPLATE = [
  "Repair the failed verifier result.",
  "",
  "Verifier Task ID: {{verifierTaskId}}",
  "",
  "## Verifier Output",
  "```json",
  "{{verifierOutputJson}}",
  "```",
  "",
  "Return structured JSON. Include changedFiles, checks, artifacts, and problems.",
].join("\n");
